name: fmk
channels:
    - conda-forge
    - defaults
    - gimli
dependencies:
    - python=3.7
    - pygimli=1.1.1
    - pandas
    - obspy=1.2.2
    - pyyaml
    - ipython
    - jupyter
    - pyvistaqt
    - build
