wavelet:
    length: 1.024
    frequency: 100
    sampling_rate: 2000
    pretrigger: 0.02
    
dataset:
    number: 1
    names: [syn_data]
    noise: 1
    noise_level: 0.00001
    missing_shots: 1
    broken_geophones: 1
    wrong_polarity: 1

model:
    velmap: [[1, 750], [2, 2500], [3, 4000]]
    quality: 32
    area: 10
    smooth: [1, 10]
    sec_nodes: 2
    
traveltimes:
    noise_relative: 0.
    noise_absolute: 0.
