wavelet:
    length: 1.024
    frequency: 100
    sampling_rate: 2000
    pretrigger: 0.02

dataset:
    number: 1
    names: [Dataset_1]
    noise: 0
    noise_level: 1.e-5
    missing_shots: 0
    broken_geophones: 0
    wrong_polarity: 0

model:
    velmap: [[1, 750], [2, 3000]]
    layers: [[1, 3], [2, 10]]
    quality: 32
    area: 10
    smooth: [1, 10]
    sec_nodes: 3
    
traveltimes:
    noise_relative: 0.
    noise_absolute: 0.
